sudo: false
dist: trusty
language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_script:
- chmod +x scripts/docs
script:
- npm run lint
- npm run cover -- --runInBand
after_script:
- npm run report-coverage
after_success:
- scripts/docs
env:
  global:
    secure: 
branches:
  only:
  - master
